<div class="custom-store">
	<div class="custom-form-language">
	    <div id="custom-select-language" class="custom-dropdown-language">
			<div class="value show_language">
	        			IT            
				<span><i class="fa fa-angle-down"></i></span>
			</div>
			<ul class="select-language-content" style="display: none;">
				<li>
					<a href="#">IT</a>
				</li>
				<li>
					<a href="#">EN</a>
				</li>
			</ul>
		</div>
	</div>
</div>