
<div class="custom-footer">
 <div class="custom-subscribe col-md-12 col-sm-12">
    <div class="content-subscribe">
       <div class="block-title">
        <strong><span><?php echo __('Iscriviti alla newsletter') ?></span></strong>
    </div>
    <form class="form subscribe"
    novalidate
    action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
    method="post"
    data-mage-init='{"validation": {"errorClass": "mage-error"}}'
    id="newsletter-validate-detail">
    <div class="field newsletter">
        <div class="control">
            <input name="email" type="email" id="newsletter"
            placeholder="<?php /* echo __('Enter your email address') */?>"
            data-validate="{required:true, 'validate-email':true}"/>
        </div>
    </div>
    <div class="actions">
        <button class="action subscribe button" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
            <span><span><i class="fa fa-paper-plane"></i></span></span></span>
        </button>
    </div>
    <div class="checkbox-required checkbox-subscribe">
     <div class="checkbox-left check_same">
        <input type="checkbox" value="on" name="Privacy" title="Privacy Policy" id="inputPrivacy" class="checkbox required-entry checkbox-newsletter">
        <label for="privacy" class="lable-privacy"><?php echo __('Ho letto e accetto l’informativa sulla') ?><a href="/privacy-policy-cookie-restriction-mode/" target="_blank"><?php echo __('privacy policy') ?></a></label>
    </div>
</div>
</form>	
</div>
</div>
<div class="custom-links">
    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_links')->toHtml(); ?>
</div>
</div>

<script>
    require(["jquery"], function($){
        if($(window).width() > 770){
            var submitIcon = $('.searchbox-icon');
            var inputBox = $('.searchbox-input');
            var searchBox = $('.searchbox');
            var isOpen = false;
            submitIcon.click(function(){
                if(isOpen == false){
                    searchBox.addClass('searchbox-open');
                    inputBox.focus();
                    isOpen = true;
                } else {
                    searchBox.removeClass('searchbox-open');
                    inputBox.focusout();
                    isOpen = false;
                }
            });  
            submitIcon.mouseup(function(){
                return false;
            });
            searchBox.mouseup(function(){
                return false;
            });
            $(document).mouseup(function(){
                if(isOpen == true){
                    $('.searchbox-icon').css('display','block');
                    submitIcon.click();
                }
            });
        };
        $( document ).ready(function(){
            var inputVal = $('#search').val();
            inputVal = $.trim(inputVal).length;
            if( inputVal !== 0){
                $('.searchbox-icon').css('display','none');
            } else {
                $('.searchbox-input').val('');
                $('.searchbox-icon').css('display','block');
            }
        });
            // function buttonUp(){
            //     var inputVal = $('#search').val();
            //     inputVal = $.trim(inputVal).length;
            //     if( inputVal !== 0){
            //         $('.searchbox-icon').css('display','none');
            //     } else {
            //         $('.searchbox-input').val('');
            //         $('.searchbox-icon').css('display','block');
            //     }
            // }
            $(".qtybutton").on("click", function() {
                var $button = $(this);
                var oldValue = $button.parent().find("input").val();
                if ($button.text() == "+") {
                  var newVal = parseFloat(oldValue) + 1;
              } else {
                   // Don't allow decrementing below zero
                   if (oldValue > 1) {
                    var newVal = parseFloat(oldValue) - 1;
                } else {
                    newVal = 1;
                }
            }
            $button.parent().find("input").val(newVal);
        });
            function scrollNav() {

                $('.nav a').click(function(){  

                    $('html, body').stop().animate({

                        scrollTop: $( $(this).attr('href') ).offset().top

                    }, 400);

                    return false;

                });

            }

            scrollNav();
            $('#custom-select-language').click(function(){
                $('.select-language-content').slideToggle();
            });
        });
    </script>
    <script type="text/javascript">
        require([
         "jquery",
         "owlcarousel/minjs"
         ], function($,owlCarousel){
            $('.pikalong.owl-carousel').owlCarousel({
                loop: true,
                margin: 10,
                responsiveClass: true,
                responsive: {
                    0: {
                        items: 2
                    },
                    600: {
                        items: 3
                    },
                    1000: {
                        items: 3,
                        loop: true,
                        margin: 20
                    }
                },
                autoplay:false,
                dots: true
        // autoplayTimeout:1000,
    });
        });
    </script>



    