<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php

/**
*  General template for displaying group of blocks devided into sections
*/

$group = $block->getGroupName();
$groupCss = $block->getGroupCss();
$groupBehavior = $block->getGroupBehaviour() ? $block->getGroupBehaviour() : '{"tabs":{"openedState":"active"}}';
?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames($group, 'getChildHtml')):?>
    <div class="sections <?= /* @escapeNotVerified */ $groupCss ?>">


        <a class="custom-logo" href="http://127.0.0.1/m22-ogm/" title="">
            <img src="http://127.0.0.1/m22-ogm/pub/media/logo/stores/1/logo.png" alt="" width="130" height="50">
        </a>

        <?php $layout = $block->getLayout(); ?>
        <div class="section-items <?= /* @escapeNotVerified */ $groupCss ?>-items" data-mage-init='<?= /* @escapeNotVerified */ $groupBehavior ?>'>
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html) && ($block->getUseForce() != true)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div class="section-item-title <?= /* @escapeNotVerified */ $groupCss ?>-item-title" data-role="collapsible">
                    <a class="<?= /* @escapeNotVerified */ $groupCss ?>-item-switch" data-toggle="switch" href="#<?= /* @escapeNotVerified */ $alias ?>"><?= /* @escapeNotVerified */ $label ?></a>
                </div>
                <div class="section-item-content <?= /* @escapeNotVerified */ $groupCss ?>-item-content" id="<?= /* @escapeNotVerified */ $alias ?>" data-role="content"><?= /* @escapeNotVerified */ $html ?></div>
            <?php endforeach;?>
        </div>


        <!-- add social header -->
        <div class="vertical-header-custom">
            <div class="vertical-social">
                <a target="_blank" href="https://www.facebook.com/OGM-plant-320840181696716/"><i class="fa fa-facebook"></i></a>
                <a target="_blank" href="https://www.instagram.com/ogm_plant/"><i class="fa fa-instagram"></i></a>
            </div>
            <div class="block-info">
                <ul>
                    <li><strong>EM Industries</strong></li>
                    <li>Via Mantova 28C</li>
                    <li>37069 Villafranca di</li>
                    <li>Verona (VR)</li>
                    <li class="telefo">P.IVA: 04496030232</li>
                    <li><a href="mailto:info@ogm-plant.com">info@ogm-plant.com</a></li>
                </ul>
            </div>
        </div>
    </div>
<?php endif; ?>

