<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var $block \Magento\Checkout\Block\Cart */
?>
<?php if (!$block->hasError()): ?>
<?php $methods = $block->getMethods('methods') ?: $block->getMethods('top_methods') ?>
<ul class="checkout methods items checkout-methods-items">
	<li class="item custom button">
        <?php if ($block->getContinueShoppingUrl()): ?>
            <a class="continue"
               href="<?= $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
               title="<?= $block->escapeHtml(__('Continue Shopping')) ?>">
                <span><?= /* @escapeNotVerified */ __('TORNA AGLI ACQUISTI') ?></span>
            </a>
        <?php endif; ?>
	</li>

<?php foreach ($methods as $method): ?>
    <?php if ($methodHtml = $block->getMethodHtml($method)): ?>
    <li class="item"><?= /* @escapeNotVerified */ $methodHtml ?></li>
    <?php endif; ?>
<?php endforeach; ?>
</ul>
<?php endif; ?>
